input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [service] {
    mutate {
      add_tag => ["cybersec"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cybersec-%{+YYYY.MM.dd}"
    ecs_compatibility => disabled
  }
  stdout { codec => rubydebug { metadata => false } }
}
